#joysondemo

trigger:
 branches:
    include:
      - master
pr:
 branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "junit"
    displayName: "junit stage"
    jobs:
      #job: "junitTest"
        #displayName: "Running unit test"
        #step:
         #-script: echo "Running Spring demo app unit test