#joysondemo

trigger:
 branches:
    include:
      - master
pr:
 branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "junit"
    displayName: "junit stage"
    jobs:
      - job: "JunitTest"