#joysondemo

trigger:
 branches:
    include:
      - master
pr:
 branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "junit"
    displayName: "junit stage"
    jobs:
      -job: "junitTest"
        #displayName: "Running unit test"
        step:
         -script: echo "Running Spring demo app unit test"
         - task: Maven@4
           inputs:
             mavenPomFile: 'pom.xml'
             goals: 'test'
             publishJUnitResults: true
             testResultsFiles: '**/surefire-reports/TEST-*.xml'
             codeCoverageToolOption: 'JaCoCo'
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: false
             effectivePomSkip: false
             sonarQubeRunAnalysis: false
             checkStyleRunAnalysis: true
             pmdRunAnalysis: true
            
  - stage: "BuildArtifact"
    displayName: "Building Artifact"
    jobs:
      -job: "BuildArtifact"
       displayName: Building Artifact
       steps:
       - task: Maven@4
         inputs:
           mavenPomFile: 'pom.xml'
           goals: 'clean package'
           publishJUnitResults: true
           testResultsFiles: '**/surefire-reports/TEST-*.xml'
           javaHomeOption: 'JDKVersion'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false
           effectivePomSkip: false
           sonarQubeRunAnalysis: false